### PR TITLE
Add extra information displays

### PR DESCRIPTION
**Pull request by akirak**
This PR contains patches for displaying a list of current backends in the modeline, which I introduced in [this reddit thread](https://www.reddit.com/r/emacs/comments/e79l6c/my_companyposframe_configuration_displaying/). It also contains a couple of other features for displaying extra information in the posframe.

- Display a list of current backends in the modeline. 
- Display metadata of the current selection below the visible candidates.
- ~~Allow formatting each candidate via a custom function. The default is appending metadata of the candidate if any.~~

The faces are customizable.

Below is a screenshot which shows an example in TypeScript (with tide-mode) with the default configuration:

image

### CODE REVIEW

**Comment by tumashu** [comment]
The display seem to have some problem:

图片

**Comment by akirak** [comment]
It looks like a scrollbar, but I am not sure why it is shown. I will look into the issue.

**Comment by akirak** [comment]
The scroll bar appears even in the original master branch, so I don't think it is my fault.

image

**Comment by tumashu** [comment]
I mean that  scrollbar is not appear at the right border

**Comment by tumashu** [comment]
图片

**Comment by akirak** [comment]
Sorry for bothering you. What about now?

**Comment by tumashu** [comment]
I think the three face's define have some problem, 
for I can not use customize-face to set them.



```
(defface company-posframe-inactive-backend-name
  '((nil :inherit mode-line))
  "Face for the active backend name in the header line.")

(defface company-posframe-active-backend-name
  '((nil :inherit mode-line-emphasis))
  "Face for the active backend name in the header line.")

(defface company-posframe-metadata
  '((nil :inherit 'font-lock-comment-face))
  "Face for the metadata footer (not the backend indicator).")

```
nil or t or default?

```
(defface company-tooltip-search
  '((default :inherit highlight))
  "Face used for the search string in the tooltip.")
```

**Comment by tumashu** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Faces.html#Defining-Faces

**Comment by akirak** [comment]
Thanks, I think I've fixed the issue.

**Comment by tumashu** [comment]
I do not know whether it is a good idea enable two feature by default, merged first, and see other users's opinion.

**Comment by akirak** [comment]
Thanks, to disable the footer, you can change the default value of `company-posframe-show-metadata` to nil at any time.

**Pull request merged**
